In [3]:
import sys, os, io, json, numpy as np, random
#from sklearn.metrics import roc_auc_score
import xgboost as xgb
import tensorflow as tf
from importlib import reload
import split
reload(split)
from split import tf_print
#from split import split_graph, split_interface, make_split
import graphviz
from sklearn import metrics

In [5]:
x=tf.ones([1, 2])
y=tf.zeros([1, 3])
p = x*x
p = tf_print(p, [x, y], "hello")
with tf.Session() as s:
    p.eval()

hello [[0. 0. 0.]]
hello [[1. 1.]]


In [35]:
def take_along_axis(arr, indices):
    # arr (n x m)
    m = tf.shape(features)[1]
    r = tf.range(m)
    taken_arr = tf.gather(tf.reshape(features, (-1,)), indices * m + r, axis=0)
    return taken_arr

graph = tf.Graph()
with graph.as_default():
    features = tf.placeholder(dtype=tf.float64)
    ax = tf.transpose(tf.nn.top_k(-tf.transpose(features), k=tf.shape(features)[-2]).indices)
    #sorted_thresholds = tf.gather(features, ax, axis=0)  # N x M x M 
    sorted_thresholds = take_along_axis(features, ax)

In [36]:
f_example = np.array([[1, 2, 3, 4, 5],
                     [3, 2, 4.5, -10, 5]], dtype=np.float32).T

In [37]:
with tf.Session(graph=graph) as s:
    ax_v, sf_v = s.run([ax, sorted_thresholds], {features: f_example})
print(ax_v, ax_v.shape)
print()
print(sf_v, sf_v.shape)

[[0 3]
 [1 1]
 [2 0]
 [3 2]
 [4 4]] (5, 2)

[[  1.  -10. ]
 [  2.    2. ]
 [  3.    3. ]
 [  4.    4.5]
 [  5.    5. ]] (5, 2)


In [67]:
ax1 = np.array([[1, 2, 3, 4, 5],
                [3, 2, 4, 1, 5],
                [5,4,3,2,1],
                [4,5,3,1,2]
               ], dtype=np.int32).T-1

In [68]:
ax1

array([[0, 2, 4, 3],
       [1, 1, 3, 4],
       [2, 3, 2, 2],
       [3, 0, 1, 0],
       [4, 4, 0, 1]], dtype=int32)

In [69]:
cond = ax1[:,1] < 2.5
cond*1

array([1, 1, 0, 1, 0])

In [70]:
cond[ax1]*1

array([[1, 0, 0, 1],
       [1, 1, 1, 0],
       [0, 1, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 1, 1]])

In [71]:
np.arange(5)[cond]

array([0, 1, 3])

In [79]:
reindex = np.cumsum(cond)-1
#reindex[ax1].ravel()[cond[ax1].ravel()]
reindex[ax1].T[cond[ax1].T].reshape((ax1.shape[1], -1)).T

array([[0, 1, 2, 2],
       [1, 2, 1, 0],
       [2, 0, 0, 1]])

In [82]:
def new_ax(ax, cond):
    reindex = np.cumsum(cond)-1
    axT = ax.T
    return reindex[axT][cond[axT]].reshape((ax1.shape[1], -1)).T

In [83]:
new_ax(ax1, cond)

array([[0, 1, 2, 2],
       [1, 2, 1, 0],
       [2, 0, 0, 1]])

# Cumsum vs nn.conv2d

In [124]:
example2 = np.array([[1,2,4,8,16,32,64],
                    [16,8,4,2,1,0,-1],
                    [1,1,1,1,1, 1, 1]
                    ]).T
def mycumsum0(inputarr):
    s = tf.shape(inputarr)
    z0 = tf.zeros((s[0]//2, s[1]), dtype=inputarr.dtype)
    z1 = tf.concat((z0,inputarr), axis=0)
    s1 = tf.shape(z1)
    reshaped = tf.reshape(z1, (1, s1[0], s1[1], 1))
    filter = tf.ones((s[0], 1, 1, 1), dtype=reshaped.dtype)
    cum = tf.nn.conv2d(reshaped, filter, strides=(1,1,1,1), padding="SAME")
    cum = tf.reshape(cum, (s1[0], s1[1]))[:s[0],:]
    return cum

graph2 = tf.Graph()
with graph2.as_default():
    inputarr = tf.placeholder(dtype=tf.float64)
    cum = mycumsum0(inputarr)

with tf.Session(graph=graph2) as s:
    cum_v, = s.run([cum], {inputarr: example2})
cum_v, cum_v.shape

(array([[  1.,  16.,   1.],
        [  3.,  24.,   2.],
        [  7.,  28.,   3.],
        [ 15.,  30.,   4.],
        [ 31.,  31.,   5.],
        [ 63.,  31.,   6.],
        [127.,  30.,   7.]]), (7, 3))

# test cumsum time

In [2]:
b, a = 1000, 100000
#b, a = 100, 1000000
vertical =  np.random.random((a, b))

In [3]:
other = np.random.random((a*2, b//2))

In [4]:
config = tf.ConfigProto(
        device_count = {'GPU': 0}
    )

In [5]:
graph = tf.Graph()
with graph.as_default():
    features = tf.placeholder(dtype=tf.float64)    
    result = tf.cumsum(features, axis=1)
    for _ in range(99):
        result = tf.cumsum(result, axis=0)
    # result = tf.cumsum(result, axis=0)
    # result = tf.cumsum(result, axis=0)
    # result = tf.cumsum(result, axis=0)
    final_result = tf.reduce_sum(result)

In [6]:
%%time
with tf.Session(graph=graph) as s:
    result_v, = s.run([final_result], {features: vertical })
    # print('result_v =', result_v)

CPU times: user 1.11 s, sys: 1.03 s, total: 2.14 s
Wall time: 7.18 s


In [7]:
%%time
with tf.Session(graph=graph) as s:
    result_v, = s.run([final_result], {features: other})

CPU times: user 1.31 s, sys: 596 ms, total: 1.91 s
Wall time: 11.2 s


In [64]:
vertical.shape, horizontal.shape

((2000, 30000), (30000, 2000))

### Extra gather

In [28]:
graph = tf.Graph()
with graph.as_default():
    features = tf.placeholder(dtype=tf.float64)
    ax = tf.placeholder(dtype=tf.int32)
    extra = tf.gather(features, ax, axis=0)
    extra = tf.transpose(extra, perm=[1, 0, 2], name='transpose')
    
f = np.array([[1, 2, 3, 4], [10, 20, 30, 40], [7, 13, 22, 31]])
a = np.array([[0,1,2,3], [3,2,1,0]], dtype=np.int32)
with tf.Session(graph=graph) as s:
    result_v, = s.run([extra], {features: f.T, ax: a.T})

print(result_v.shape)
result_v

(2, 4, 3)


array([[[ 1., 10.,  7.],
        [ 2., 20., 13.],
        [ 3., 30., 22.],
        [ 4., 40., 31.]],

       [[ 4., 40., 31.],
        [ 3., 30., 22.],
        [ 2., 20., 13.],
        [ 1., 10.,  7.]]])

### test

In [29]:
leaf_indices = np.array([1, 1, 2, 2, 0])

In [31]:
leaf_values = np.array([[0.1], [0.2], [0.3]])

In [32]:
leaf_values[leaf_indices, 0]

array([0.2, 0.2, 0.3, 0.3, 0.1])

In [35]:
leaf_values_w = np.array([[0.1, 10], [0.2, 11], [0.3, 12]])

In [37]:
leaf_values_w[leaf_indices, :]

array([[ 0.2, 11. ],
       [ 0.2, 11. ],
       [ 0.3, 12. ],
       [ 0.3, 12. ],
       [ 0.1, 10. ]])